apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: example-apps
  namespace: flux-system
spec:
  image: dzikrihuda/example-apps
  interval: 30s
  secretRef:
    name: dockerhub-key
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: example-apps
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: example-apps
  policy:
    semver:
      range: '>=0.0.1'
---
apiVersion: v1
kind: Secret
metadata:
  name: your-ip-configs
  namespace: playground-dfgjkt
type: Opaque
stringData:
  APP_NAME: "example-apps"
  ENV: "production"
  PORT: "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-ip
  namespace: playground-dfgjkt
  labels:
    app: example-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-apps
  template:
    metadata:
      labels:
        app: example-apps
    spec:
      imagePullSecrets:
        - name: dockerhub-key
      containers:
        - name: example-apps
          image: dzikrihuda/example-apps:1.1.0 # {"$imagepolicy": "flux-system:your-ip"}
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: "your-ip-configs"
---
apiVersion: v1
kind: Service
metadata:
  name: example-apps
  namespace: playground-dfgjkt
  labels:
    app: example-apps
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: example-apps
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-apps
  namespace: playground-dfgjkt
spec:
  rules:
    - host: ipinfo.dwyor.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: your-ip
                port:
                  number: 80
  ingressClassName: traefik
